export const resList = [
  {
    id: "rest001",
    name: "Tasty Bites",
    image: "https://picsum.photos/300/200?food=1",
    address: {
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    cuisine: ["Italian", "Mediterranean"],
    rating: 4.5,
    priceRange: "$$",
  },
  {
    id: "rest002",
    name: "Sushi Palace",
    image: "https://picsum.photos/300/200?food=2",
    address: {
      street: "456 Ocean Ave",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
    },
    cuisine: ["Japanese", "Sushi"],
    rating: 4.7,
    priceRange: "$$$",
  },
  {
    id: "rest003",
    name: "Burger Barn",
    image: "https://picsum.photos/300/200?food=3",
    address: {
      street: "789 Grill Lane",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    cuisine: ["American", "Burgers"],
    rating: 4.3,
    priceRange: "$",
  },
  {
    id: "rest004",
    name: "Spice Garden",
    image: "https://picsum.photos/300/200?food=4",
    address: {
      street: "101 Curry Road",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
    },
    cuisine: ["Indian", "Vegetarian"],
    rating: 4.6,
    priceRange: "$$",
  },
  {
    id: "rest005",
    name: "Taco Fiesta",
    image: "https://source.unsplash.com/random/300x200/?tacos",
    address: {
      street: "202 Avocado Street",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
    },
    cuisine: ["Mexican", "Tex-Mex"],
    rating: 4.4,
    priceRange: "$",
  },
  {
    id: "rest006",
    name: "Pho King",
    image: "https://source.unsplash.com/random/300x200/?pho",
    address: {
      street: "303 Noodle Blvd",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
    },
    cuisine: ["Vietnamese", "Noodles"],
    rating: 4.8,
    priceRange: "$",
  },
  {
    id: "rest007",
    name: "Pizza Heaven",
    image: "https://source.unsplash.com/random/300x200/?pizza",
    address: {
      street: "404 Cheese Street",
      city: "Boston",
      state: "MA",
      zipCode: "02108",
    },
    cuisine: ["Italian", "Pizza"],
    rating: 4.5,
    priceRange: "$$",
  },
  {
    id: "rest008",
    name: "Dragon Wok",
    image: "https://source.unsplash.com/random/300x200/?chinese-food",
    address: {
      street: "505 Bamboo Road",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    cuisine: ["Chinese", "Asian Fusion"],
    rating: 4.2,
    priceRange: "$$",
  },
  {
    id: "rest009",
    name: "The Steakhouse",
    image: "https://source.unsplash.com/random/300x200/?steak",
    address: {
      street: "606 Meat Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
    },
    cuisine: ["American", "Steak"],
    rating: 4.9,
    priceRange: "$$$",
  },
  {
    id: "rest010",
    name: "Green Leaf Cafe",
    image: "https://source.unsplash.com/random/300x200/?salad",
    address: {
      street: "707 Veggie Lane",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
    },
    cuisine: ["Vegan", "Organic"],
    rating: 4.7,
    priceRange: "$$",
  },
];
